
from pyecharts import online
urls = [
    "https://mp.weixin.qq.com/s/u6_1jLQ7EKVdN0YDZmsCCQ",
    "https://mp.weixin.qq.com/s/uZHrNOC5cJ8vsnDz99mz9Q",
    "https://mp.weixin.qq.com/s/E0Ygl_6Rf44Voj4E9VoU5Q",
    "https://mp.weixin.qq.com/s/mTgNo9MtofhKH6fr3z7KDA",
    "https://mp.weixin.qq.com/s/glPk6oSe84kqYwSPQBfKjQ",
    "https://mp.weixin.qq.com/s/RpmPswmiHjfIqbHYI9DxEQ",
    "https://mp.weixin.qq.com/s/jEuuInV8ypJ08NJyzIhjAw",
    "https://mp.weixin.qq.com/s/X41s2Qyjj4G6Qjrtm3wg2Q",
    "https://mp.weixin.qq.com/s/H9pFblkVoqWe-n633pizOA",
    "https://mp.weixin.qq.com/s/UiBSE67xRdEhs8Uk_2UDgQ",
    "https://mp.weixin.qq.com/s/mRwFgv5FCP4oP3oyQlCwHg",
    "https://mp.weixin.qq.com/s/LGE8NOcXLnBFaPd4CrykNw",
    "https://mp.weixin.qq.com/s/tw1oCQJC3nXsoyHOnCBQBA",
    "https://mp.weixin.qq.com/s/RMjL7LHXaooZ-8R29t4Png",
    "https://mp.weixin.qq.com/s/mO29Bt8tksyGl9KrdAJ3bg",
    "https://mp.weixin.qq.com/s/yZfS0WjJxOAlxCgOfJYIyg",
    "https://mp.weixin.qq.com/s/ZFYee6OOVqE2rWVEjn5iUA"
]

aug_urls = [
    "https://mp.weixin.qq.com/s/mPoeE1RFYY5d2ja-PDKKtg",
    "https://mp.weixin.qq.com/s/vjEgCs3tf3hL8mMjha9d-w",
    "https://mp.weixin.qq.com/s?__biz=MzI1OTExNDY1NQ==&tempkey=OTc3X1FqaEswUjRDeDVjcUNZMkVCQ0VxWlZnNmdaZEpFNGVXcjhXZzZPaHBwd015eXVZaHVWLTNNaWdjSUF0UEtoY09XRm1LYVdsMkkyMjhId0xPOExsUlV3Y1pkTUJTZzFjT3JyVlJJQkVvVzBTeDVoeW1tN1RVc3JjRXJPSjV2c1lEVTNCa0ZINHRNMDlFRV9tNU9YQkZqZmM0Yktxc240MS15dEkzZGd%2Bfg%3D%3D&chksm=71825d0f46f5d419479d824b68add0bb1bd3178d902a1012545671b70d5b29d77d1cc889ffea#rd",
    "https://mp.weixin.qq.com/s/9DCyOltIpwiNMq-hU0Fqbw",
    "https://mp.weixin.qq.com/s/dpM4TtuiRX5pR_1seQL6dQ",
    "https://mp.weixin.qq.com/s/SelYcXH_8u0QVjRHF33BZQ",
    "https://mp.weixin.qq.com/s/jzlF3mHhZPbbA7-1Mq55tA",
    "https://mp.weixin.qq.com/s/SCRDMniSj6VIUrzf-TwZiQ",
    "https://mp.weixin.qq.com/s/LKVDmBBG4G1HL1vvjtdu9A",
    "https://mp.weixin.qq.com/s/w12Wqu3-w3WgbE3lreiyAQ",
    "https://mp.weixin.qq.com/s/xsIQRTVbBdh4zvITwnfwFA",
    "https://mp.weixin.qq.com/s/YKas80G6tbXiAIBWkpeX6w",
    "https://mp.weixin.qq.com/s/Lk-Xzl5BUcvKmbiqWzsO7A",
    "https://mp.weixin.qq.com/s/K51ARRRysnOg8bY0WXvL8A",
    "https://mp.weixin.qq.com/s/QNGQElcNU68UFRkhpTLXVA",
    "https://mp.weixin.qq.com/s/P-0gBKEYj5nBKBIDBYPpDw",
    "https://mp.weixin.qq.com/s/2pBP8hSxoIzEgQkeCN2BQQ",
    "https://mp.weixin.qq.com/s/Pd2KXzuJ9Ov37jYdePzn0w",
    "https://mp.weixin.qq.com/s/-QUat3NBGVTSqLjYplz4EQ",
    "https://mp.weixin.qq.com/s/jHTXQo_rB4imVdaf0sXadg",
    "https://mp.weixin.qq.com/s/rbl35jyfV70OVfB6csMThw",
    "https://mp.weixin.qq.com/s/kjBtVqRqORkLHE_-CjiffA",
    "https://mp.weixin.qq.com/s/LVkm8HGcQAf3Lkh07eR2EA",
    "https://mp.weixin.qq.com/s/E-hC_7Z7Tksp0bv7fcoIdQ",
    "https://mp.weixin.qq.com/s/u6_1jLQ7EKVdN0YDZmsCCQ",
    "https://mp.weixin.qq.com/s/uZHrNOC5cJ8vsnDz99mz9Q"
]

sep_urls = [
    "https://mp.weixin.qq.com/s/u6_1jLQ7EKVdN0YDZmsCCQ",
    "https://mp.weixin.qq.com/s/uZHrNOC5cJ8vsnDz99mz9Q",
    "https://mp.weixin.qq.com/s/E0Ygl_6Rf44Voj4E9VoU5Q",
    "https://mp.weixin.qq.com/s/mTgNo9MtofhKH6fr3z7KDA",
    "https://mp.weixin.qq.com/s/glPk6oSe84kqYwSPQBfKjQ",
    "https://mp.weixin.qq.com/s/RpmPswmiHjfIqbHYI9DxEQ",
    "https://mp.weixin.qq.com/s/jEuuInV8ypJ08NJyzIhjAw",
    "https://mp.weixin.qq.com/s/X41s2Qyjj4G6Qjrtm3wg2Q",
    "https://mp.weixin.qq.com/s/H9pFblkVoqWe-n633pizOA",
    "https://mp.weixin.qq.com/s/UiBSE67xRdEhs8Uk_2UDgQ",
    "https://mp.weixin.qq.com/s/mRwFgv5FCP4oP3oyQlCwHg",
    "https://mp.weixin.qq.com/s/LGE8NOcXLnBFaPd4CrykNw",
    "https://mp.weixin.qq.com/s/tw1oCQJC3nXsoyHOnCBQBA",
    "https://mp.weixin.qq.com/s/RMjL7LHXaooZ-8R29t4Png",
    "https://mp.weixin.qq.com/s/mO29Bt8tksyGl9KrdAJ3bg",
    "https://mp.weixin.qq.com/s/yZfS0WjJxOAlxCgOfJYIyg",
    "https://mp.weixin.qq.com/s/ZFYee6OOVqE2rWVEjn5iUA",
    "https://mp.weixin.qq.com/s/u4NBoyZESOalk6kMc6eKEQ",
    "https://mp.weixin.qq.com/s/NsFIHiE3qxsQWyhGg6Xr6A",
    "https://mp.weixin.qq.com/s/ahDRXbeMxHIlOLpl3rZOIA",
    "https://mp.weixin.qq.com/s/_I8lBVQcZvXazPFi2ijssA",
    "https://mp.weixin.qq.com/s/-NezVxgIKAef-Acs9eZGDw"
]

